// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrxakRb3kgaORb2QoV6T3xRXVXZiZmKn0',
    appId: '1:396102140257:web:826feb0cdf6e416f22c520',
    messagingSenderId: '396102140257',
    projectId: 'slushies-app',
    authDomain: 'slushies-app.firebaseapp.com',
    storageBucket: 'slushies-app.firebasestorage.app',
    measurementId: 'G-ZWF93X3HMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXl0Bv3K7vi_DGh_udI6KJuQFEqq5sjrY',
    appId: '1:396102140257:android:e12648fed494573b22c520',
    messagingSenderId: '396102140257',
    projectId: 'slushies-app',
    storageBucket: 'slushies-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVT4cAk2RgUVR7HafMYyk46bXwtpZdIps',
    appId: '1:396102140257:ios:75bdf2b98e7606d422c520',
    messagingSenderId: '396102140257',
    projectId: 'slushies-app',
    storageBucket: 'slushies-app.firebasestorage.app',
    iosBundleId: 'com.example.app01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVT4cAk2RgUVR7HafMYyk46bXwtpZdIps',
    appId: '1:396102140257:ios:75bdf2b98e7606d422c520',
    messagingSenderId: '396102140257',
    projectId: 'slushies-app',
    storageBucket: 'slushies-app.firebasestorage.app',
    iosBundleId: 'com.example.app01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrxakRb3kgaORb2QoV6T3xRXVXZiZmKn0',
    appId: '1:396102140257:web:5497ba84f2fb7c7922c520',
    messagingSenderId: '396102140257',
    projectId: 'slushies-app',
    authDomain: 'slushies-app.firebaseapp.com',
    storageBucket: 'slushies-app.firebasestorage.app',
    measurementId: 'G-GL8SB6TL7D',
  );
}
